sonar.projectKey=rajdebnath1988_trading-platform
sonar.organization=rajdebnath1988
sonar.sources=services
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/coverage/**,**/public/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
sonar.coverage.exclusions=**/*
