apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trading-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - ingress.yaml
  - postgresql/statefulset.yaml
  - auth-service/deployment.yaml
  - api-gateway/rollout.yaml
  - market-data-service/deployment.yaml
  - order-service/deployment.yaml
  - portfolio-service/deployment.yaml
  - frontend/rollout.yaml
